# Be sure to restart your server when you modify this file.

# You can add backtrace silencers for libraries that you're using but don't wish to see in your backtraces.
# Rails.backtrace_cleaner.add_silencer { |line| line =~ /my_noisy_library/ }
Rails.backtrace_cleaner.add_silencer { |line| line =~ /rvm/ }

# Clean those ERB lines, we don't need the internal autogenerated
# ERB method, what we do need (line number in ERB file) is already there
Rails.backtrace_cleaner.add_filter { |line| line.sub(/(\.erb:\d+)\:in '__.*$/, "\\1") }

# You can also remove all the silencers if you're trying to debug a problem that might stem from framework code.
# Rails.backtrace_cleaner.remove_silencers!
